# Generated by Django 5.0.1 on 2024-01-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('room', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Main Lab'), (2, 'Gel Lab'), (3, 'Cold Room'), (4, 'Freezer Room'), (5, 'FACS Lab'), (6, 'Store Room'), (7, 'Wash Room')], default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
