# Generated by Django 5.0 on 2024-01-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=[(0, 'Unknown'), (1, 'Main Lab'), (2, 'Gel Lab'), (3, 'Cold Room'), (4, 'Freezer Room'), (5, 'FACS Lab'), (6, 'Store Room'), (7, 'Wash Room')]),
        ),
    ]
