# Generated by Django 4.2.7 on 2023-11-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
    ]
