# Generated by Django 5.0.1 on 2024-01-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='location.room'),
        ),
    ]
