# Generated by Django 5.0 on 2024-01-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Main Lab'), (2, 'Gel Lab'), (3, 'Cold Room'), (4, 'Freezer Room'), (5, 'FACS Lab'), (6, 'Store Room'), (7, 'Wash Room')], default=0),
        ),
    ]
