# Generated by Django 5.0.1 on 2024-01-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_location_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
