# Generated by Django 4.2.7 on 2023-12-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_created_location_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='room',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
