# Generated by Django 4.2.7 on 2023-11-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_delivery_delivery_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-delivery_date'], 'verbose_name_plural': 'deliveries'},
        ),
    ]
