# Generated by Django 4.2.7 on 2023-12-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliveryattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
