# Generated by Django 4.2.7 on 2023-12-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_delivery_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='created_by',
        ),
    ]
