# Generated by Django 4.2.7 on 2023-12-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_remove_delivery_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryattachment',
            options={'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
    ]
