# Generated by Django 4.2.7 on 2023-11-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_delivery_condition'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_condition', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Good'), (2, 'Unacceptable'), (3, 'Requires Attention')], default=0)),
                ('lot_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('in_use_date', models.DateField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
    ]
