# Generated by Django 5.0.1 on 2024-01-16 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_initial'),
        ('company', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('item', '0001_initial'),
        ('location', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inhousereagent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inhousereagent',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inhousereagentvalidation',
            name='inhouse_reagent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='item.inhousereagent'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='category.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactured_items', to='company.company'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_items', to='company.company'),
        ),
        migrations.AddField(
            model_name='itemattachment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='itemattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reagentcomponent',
            name='reagent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.inhousereagent'),
        ),
        migrations.AddField(
            model_name='reagentvalidation',
            name='authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authoriser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reagentvalidation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inhousereagentvalidation',
            name='validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.reagentvalidation'),
        ),
        migrations.AddField(
            model_name='stock',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='inhouse_reagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='item.inhousereagent'),
        ),
        migrations.AddField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='item.item'),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reagentcomponent',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.stock'),
        ),
        migrations.AddField(
            model_name='inhousereagent',
            name='components',
            field=models.ManyToManyField(related_name='inhouse_reagents', through='item.ReagentComponent', to='item.stock'),
        ),
        migrations.AddField(
            model_name='stockattachment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stockattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='location.location'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='item.stock'),
        ),
        migrations.AddField(
            model_name='stockvalidation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='item.stock'),
        ),
        migrations.AddField(
            model_name='stockvalidation',
            name='validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.reagentvalidation'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='remaining_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit'),
        ),
        migrations.AddField(
            model_name='reagentcomponent',
            name='quantity_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit'),
        ),
        migrations.AddField(
            model_name='usage',
            name='stock_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='item.stockentry'),
        ),
        migrations.AddField(
            model_name='usage',
            name='used_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usage',
            name='used_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='inhousereagentvalidation',
            unique_together={('inhouse_reagent', 'validation')},
        ),
        migrations.AlterUniqueTogether(
            name='inhousereagent',
            unique_together={('product_id', 'lot_number')},
        ),
        migrations.AlterUniqueTogether(
            name='stockvalidation',
            unique_together={('stock', 'validation')},
        ),
        migrations.AlterUniqueTogether(
            name='stockentry',
            unique_together={('stock', 'ordinal_number')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'product_id')},
        ),
    ]
