# Generated by Django 5.1.1 on 2024-11-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='threshold_type',
            field=models.CharField(choices=[('U', 'Unit Based'), ('T', 'Time Based')], default='U', max_length=1),
            preserve_default=False,
        ),
    ]
