# Generated by Django 5.0.1 on 2024-01-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
        ('item', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhousereagent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
    ]
