# Generated by Django 5.0 on 2023-12-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_stock_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
