# Generated by Django 5.0.1 on 2024-01-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_inhousereagent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhousereagent',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inhousereagent',
            name='quantity_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit'),
        ),
    ]
