# Generated by Django 5.0 on 2023-12-29 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_stock_comments'),
        ('location', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-created', 'item', 'lot_number'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='in_use_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ordinal_number',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='remaining_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='remaining_unit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='total_count',
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_quantity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('ordinal_number', models.PositiveIntegerField(default=1)),
                ('in_use_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock_units', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='location.location')),
                ('remaining_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='item.stock')),
            ],
            options={
                'verbose_name': 'Stock Entry',
                'verbose_name_plural': 'Stock Entries',
                'ordering': ['stock', '-ordinal_number'],
            },
        ),
    ]
