# Generated by Django 5.0.1 on 2024-01-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_inhousereagent_quantity_inhousereagent_quantity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhousereagent',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
