# Generated by Django 5.0 on 2023-12-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_stock_options_remove_stock_in_use_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockentry',
            unique_together={('stock', 'ordinal_number')},
        ),
    ]
