# Generated by Django 5.0.1 on 2024-01-16 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_inhousereagent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhousereagent',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
