# Generated by Django 4.2.7 on 2023-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_stockitem_expiry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='lot_number',
            field=models.CharField(max_length=50),
        ),
    ]
