# Generated by Django 5.0 on 2023-12-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_stockentry_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='delivery_condition',
            new_name='condition',
        ),
    ]
