# Generated by Django 5.0 on 2024-01-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_rename_delivery_condition_stock_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockentry',
            options={'ordering': ['stock', 'ordinal_number'], 'verbose_name': 'Stock Entry', 'verbose_name_plural': 'Stock Entries'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
