# Generated by Django 5.0.1 on 2024-01-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_inhousereagent_expiry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inhousereagent',
            options={'ordering': ['name']},
        ),
        migrations.DeleteModel(
            name='InhouseReagentValidation',
        ),
    ]
