# Generated by Django 5.0 on 2024-01-03 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_stockentry_options_alter_stock_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockentry',
            options={'ordering': ['ordinal_number'], 'verbose_name': 'Stock Entry', 'verbose_name_plural': 'Stock Entries'},
        ),
    ]
