# Generated by Django 4.2.7 on 2023-11-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_options'),
        ('item', '0008_stockitem_location_alter_stockitem_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='delivery.delivery'),
        ),
    ]
