# Generated by Django 5.0.1 on 2024-01-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_inhousereagent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inhousereagent',
            options={'ordering': ['name'], 'verbose_name': 'Inhouse reagent', 'verbose_name_plural': 'Inhouse reagents'},
        ),
    ]
