# Generated by Django 4.2.7 on 2023-11-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_stockitem_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'product_id')},
        ),
    ]
