# Generated by Django 5.0 on 2024-01-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_stockentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='delivery_date',
            field=models.DateField(),
        ),
    ]
