# Generated by Django 5.0.1 on 2024-01-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_inhousereagent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
