# Generated by Django 5.0.1 on 2024-01-23 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_item_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('threshold', models.DecimalField(decimal_places=1, max_digits=10)),
                ('last_checked', models.DateTimeField(null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.DateTimeField(null=True)),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_watchlists', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_watchlists', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='item.stock')),
            ],
            options={
                'verbose_name': 'Watch List',
                'verbose_name_plural': 'Watch Lists',
                'ordering': ['-last_checked'],
            },
        ),
    ]
