# Generated by Django 5.0 on 2024-01-06 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_stockattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='stock',
        ),
        migrations.AddField(
            model_name='usage',
            name='stock_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='item.stockentry'),
            preserve_default=False,
        ),
    ]
