# Generated by Django 5.0.1 on 2024-01-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='notification_sent',
            new_name='notification',
        ),
    ]
