# Generated by Django 5.0 on 2024-01-08 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_remove_usage_stock_usage_stock_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='InhouseReagentValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhouse_reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='item.inhousereagent')),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.reagentvalidation')),
            ],
            options={
                'unique_together': {('inhouse_reagent', 'validation')},
            },
        ),
    ]
