# Generated by Django 5.0.1 on 2024-01-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_rename_notification_sent_watchlist_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='last_updated_by',
        ),
    ]
