# Generated by Django 4.2.7 on 2023-11-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_item_last_updated_item_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='ordinal_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
