# Generated by Django 5.0.1 on 2024-01-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_remove_watchlist_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
