# Generated by Django 5.0 on 2024-01-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_alter_reagentvalidation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inhousereagentvalidation',
            options={'ordering': ['-validation__created']},
        ),
        migrations.AlterModelOptions(
            name='stockvalidation',
            options={'ordering': ['-validation__created']},
        ),
    ]
