# Generated by Django 5.0 on 2024-01-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_watchlist_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='is_active',
        ),
    ]
