# Generated by Django 5.0 on 2024-01-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_alter_inhousereagentvalidation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-delivery_date', 'item', 'lot_number'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
