# Generated by Django 5.0 on 2024-01-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_alter_stock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhousereagent',
            name='lot_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='inhousereagent',
            unique_together={('product_id', 'lot_number')},
        ),
    ]
