# Generated by Django 5.0 on 2024-01-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_alter_stock_options_stock_inhouse_reagent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhousereagent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reagents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inhousereagent',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reagents', to=settings.AUTH_USER_MODEL),
        ),
    ]
