# Generated by Django 4.2.7 on 2023-12-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_alter_stockitem_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattachment',
            name='item',
        ),
    ]
