# Generated by Django 4.2.7 on 2023-12-10 19:09

import attachment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_remove_itemattachment_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemattachment',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='item.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemattachment',
            name='file',
            field=models.FileField(upload_to=attachment.models.UploadToPathAndRename('attachments'), verbose_name='file'),
        ),
    ]
