# Generated by Django 4.2.7 on 2023-12-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_itemattachment_item_alter_itemattachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattachment',
            name='item',
        ),
    ]
