# Generated by Django 4.2.7 on 2023-12-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_remove_itemattachment_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemAttachment',
        ),
    ]
