# Generated by Django 4.2.7 on 2023-12-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_alter_stockitem_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
