# Generated by Django 4.2.7 on 2023-12-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0028_alter_stockitem_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tests',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='remaining_tests',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='remaining_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='remaining_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
