# Generated by Django 4.2.7 on 2023-12-16 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0029_item_tests_item_volume_item_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_tests', models.PositiveIntegerField(default=0)),
                ('used_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_date', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.stockitem')),
                ('usage_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
