# Generated by Django 4.2.7 on 2023-12-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0030_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='volume_unit',
            field=models.CharField(blank=True, choices=[('l', 'Litre'), ('ml', 'Millilitre'), ('ul', 'Microlitre')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('mg', 'Milligrams'), ('ug', 'Micrograms')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='remaining_volume_unit',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='remaining_weight_unit',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
