# Generated by Django 4.2.7 on 2023-12-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0031_item_volume_unit_item_weight_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='volume_unit',
            field=models.CharField(blank=True, choices=[('l', 'l'), ('ml', 'ml'), ('μl', 'μl')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('μg', 'μg')], max_length=2, null=True),
        ),
    ]
