# Generated by Django 4.2.7 on 2023-12-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0032_alter_item_volume_unit_alter_item_weight_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
