# Generated by Django 4.2.7 on 2023-12-19 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_delivery_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0005_location_room_alter_location_name'),
        ('item', '0033_alter_stockitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_tests', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('remaining_volume', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('remaining_volume_unit', models.CharField(max_length=2, null=True)),
                ('remaining_weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('remaining_weight_unit', models.CharField(max_length=2, null=True)),
                ('delivery_condition', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Good'), (2, 'Unacceptable'), (3, 'Requires Attention')], default=0)),
                ('lot_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ordinal_number', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='delivery.delivery')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='item.item')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='location.location')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.RemoveField(
            model_name='usage',
            name='stock_item',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.AddField(
            model_name='usage',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.stock'),
            preserve_default=False,
        ),
    ]
