# Generated by Django 4.2.7 on 2023-12-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0034_stock_remove_usage_stock_item_delete_stockitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='remaining_volume',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='remaining_weight',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
