# Generated by Django 4.2.7 on 2023-12-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0035_alter_stock_remaining_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='remaining_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='remaining_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
