# Generated by Django 4.2.7 on 2023-12-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0036_alter_stock_remaining_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cas_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
