# Generated by Django 4.2.7 on 2023-12-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0037_item_cas_number_alter_stock_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='item',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='item',
            name='volume_unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight_unit',
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('tests', 'Tests'), ('μl', 'Microlitre'), ('ml', 'Mililitre'), ('l', 'Litre'), ('μg', 'Microgram'), ('mg', 'Miligram'), ('g', 'Gram'), ('kg', 'Kilogram')], max_length=10, null=True),
        ),
    ]
