# Generated by Django 4.2.7 on 2023-12-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0038_remove_item_tests_remove_item_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('tests', 'tests'), ('μl', 'μl'), ('ml', 'ml'), ('l', 'l'), ('μg', 'μg'), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg')], max_length=10, null=True),
        ),
    ]
