# Generated by Django 4.2.7 on 2023-12-21 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0039_alter_item_quantity_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='remaining_tests',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='remaining_volume',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='remaining_volume_unit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='remaining_weight',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='remaining_weight_unit',
        ),
        migrations.AddField(
            model_name='stock',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='remaining_quantity_unit',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
