# Generated by Django 4.2.7 on 2023-12-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0042_inhousereagent_unit_inhousereagentcomponent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
    ]
