# Generated by Django 4.2.7 on 2023-12-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0043_remove_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='remaining_quantity_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit'),
        ),
    ]
