# Generated by Django 4.2.7 on 2023-12-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0045_alter_inhousereagentcomponent_qunatity_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InhouseReagentComponent',
            new_name='ReagentComponent',
        ),
    ]
