# Generated by Django 4.2.7 on 2023-12-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0046_rename_inhousereagentcomponent_reagentcomponent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reagentcomponent',
            old_name='qunatity_unit',
            new_name='quantity_unit',
        ),
    ]
