# Generated by Django 4.2.7 on 2023-12-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0048_inhousereagent_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhousereagent',
            name='components',
            field=models.ManyToManyField(related_name='inhouse_reagents', through='item.ReagentComponent', to='item.stock'),
        ),
        migrations.AlterField(
            model_name='reagentcomponent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.stock'),
        ),
    ]
