# Generated by Django 4.2.7 on 2023-12-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0049_alter_inhousereagent_components_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reagentcomponent',
            old_name='item',
            new_name='stock',
        ),
    ]
