# Generated by Django 4.2.7 on 2023-12-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0053_alter_usage_used_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='used_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit'),
        ),
    ]
