# Generated by Django 4.2.7 on 2023-12-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0054_alter_usage_used_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity_unit',
        ),
        migrations.RemoveField(
            model_name='reagentcomponent',
            name='quantity_unit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='remaining_quantity_unit',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='used_unit',
        ),
    ]
