# Generated by Django 4.2.7 on 2023-12-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0055_remove_item_quantity_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit'),
        ),
        migrations.AddField(
            model_name='reagentcomponent',
            name='quantity_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='remaining_quantity_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit'),
        ),
    ]
