# Generated by Django 4.2.7 on 2023-12-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0056_item_quantity_unit_reagentcomponent_quantity_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='used_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.unit'),
        ),
    ]
