# Generated by Django 4.2.7 on 2023-12-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0057_usage_used_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='remaining_quantity_unit',
            new_name='remaining_unit',
        ),
    ]
