# Generated by Django 4.2.7 on 2023-12-24 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0058_rename_remaining_quantity_unit_stock_remaining_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='item.stock'),
        ),
    ]
