# Generated by Django 4.2.7 on 2023-12-25 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0059_alter_usage_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_attachments', to=settings.AUTH_USER_MODEL),
        ),
    ]
