# Generated by Django 4.2.7 on 2023-12-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0060_alter_itemattachment_uploaded_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-created', '-ordinal_number'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
