# Generated by Django 4.2.7 on 2023-12-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0061_alter_stock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reagentvalidation',
            options={'ordering': ['-validated']},
        ),
        migrations.AlterField(
            model_name='reagentvalidation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_REQUIRED', 'Not Required')], default='PENDING', max_length=15),
        ),
    ]
