# Generated by Django 4.2.7 on 2023-12-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0062_alter_reagentvalidation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reagentvalidation',
            old_name='notes',
            new_name='comments',
        ),
    ]
