# Generated by Django 4.2.7 on 2023-12-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0064_inhousereagent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inhousereagent',
            name='category',
        ),
    ]
