# Generated by Django 4.2.7 on 2023-12-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0065_remove_inhousereagent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='in_use_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
