services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - db_data:/app/database
    expose:
      - "8000"
    env_file:
      - .env
    restart: always


  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - static_volume:/usr/share/nginx/html/static
    - media_volume:/usr/share/nginx/html/media
    depends_on:
      - web 
    restart: always

volumes:
  static_volume:
  media_volume:
  db_data: