services:
  web:
    image: machnine/reagentree:latest
    command: /app/entrypoint.sh    
    volumes:
      - data_volume:/app/database
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    restart: always
    

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:      
      - media_volume:/usr/share/nginx/html/media
      - static_volume:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always

volumes:
  data_volume:
  media_volume:
  static_volume: