version: '3.8'

services:
  web:
    build: .
    command: bash -c "pip install -r requirements.dev && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_PASSWORD=mysecretpassword