services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - db_data:/app/database
    expose:
      - "8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

volumes:
  static_volume:
  media_volume:
  db_data: