# Generated by Django 4.2.7 on 2023-12-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_created_category_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
