# Generated by Django 5.1.8 on 2025-04-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='is_archived',
        ),
        migrations.AlterField(
            model_name='notice',
            name='expiry_date',
            field=models.DateField(help_text='The date when this notice will expire.'),
        ),
    ]
