# Generated by Django 5.1.8 on 2025-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_remove_notice_is_archived_alter_notice_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Mark this notice as archived.'),
        ),
    ]
