# Generated by Django 5.1.8 on 2025-04-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
