# Generated by Django 4.2.7 on 2023-11-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
    ]
