# Generated by Django 5.0 on 2024-01-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='initials',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
