# Generated by Django 4.2.7 on 2023-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initials',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
