# Generated by Django 5.0 on 2024-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_alter_labelsheet_label_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelsheet',
            name='label_height',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='label_width',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='margin_bottom',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='margin_left',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='margin_right',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='margin_top',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='space_x',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='space_y',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
