# Generated by Django 5.0 on 2024-01-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_alter_labelsheet_label_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelsheet',
            name='page_size',
            field=models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('LETTER', 'LETTER')], max_length=10),
        ),
    ]
