# Generated by Django 5.0 on 2024-01-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_alter_labelsheet_page_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelsheet',
            name='label_height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='label_width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='margin_bottom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='margin_left',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='margin_right',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='margin_top',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='space_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='labelsheet',
            name='space_y',
            field=models.FloatField(),
        ),
    ]
